// =============================================================================
// CSP Nonce Utilities for Next.js 14 App Router
// =============================================================================

import { headers } from 'next/headers'

/**
 * Get the CSP nonce from the request headers (Server Component only)
 * This nonce is generated by the middleware for each request
 */
export async function getNonce(): Promise<string | undefined> {
  try {
    const headersList = await headers()
    return headersList.get('x-nonce') || undefined
  } catch {
    // headers() can only be called in Server Components
    // Return undefined if called from Client Component
    return undefined
  }
}

/**
 * Create a script tag props object with the nonce
 */
export function createScriptProps(nonce: string | undefined) {
  return nonce ? { nonce } : {}
}

/**
 * Create inline script with nonce for Next.js Script component
 */
export function createInlineScriptProps(nonce: string | undefined, dangerouslySetInnerHTML: string) {
  return {
    ...(nonce ? { nonce } : {}),
    dangerouslySetInnerHTML: { __html: dangerouslySetInnerHTML },
  }
}
