#!/bin/sh
set -e

# ==============================================================================
# worb CMS - Docker Entrypoint
# Generated by CodeB CLI v4.2.0
# Date: 2026-01-07
# ==============================================================================
# Blue-Green Slot Support:
#   - SLOT environment variable indicates current slot (blue/green)
#   - Used for logging and debugging
# ==============================================================================
# v4.2.0 Changes:
#   - Improved connection status logging
#   - Added version and build info display
#   - Enhanced error handling
# ==============================================================================

# Colors for terminal output (if supported)
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo "${GREEN}[OK]${NC} $1"
}

log_warn() {
    echo "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo "${RED}[ERROR]${NC} $1"
}

echo "========================================"
echo " worb CMS Container Starting"
echo "========================================"
echo "Environment: ${NODE_ENV:-production}"
echo "Port:        ${PORT:-3000}"
echo "Hostname:    ${HOSTNAME:-0.0.0.0}"
echo "Slot:        ${SLOT:-default}"
echo "Version:     ${VERSION:-unknown}"
echo "Started:     $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
echo ""

# Load environment variables from .env file if exists
if [ -f /app/.env ]; then
    log_info "Loading from /app/.env"
    set -a
    . /app/.env
    set +a
fi

# Connection status check
echo "[Status] Checking connections..."

# Database connection check
if [ -n "$DATABASE_URL" ]; then
    DB_HOST=$(echo "$DATABASE_URL" | sed -n 's/.*@\([^:\/]*\).*/\1/p')
    DB_NAME=$(echo "$DATABASE_URL" | sed -n 's/.*\/\([^?]*\).*/\1/p')
    log_success "Database: $DB_HOST ($DB_NAME)"
else
    log_warn "Database: NOT CONFIGURED"
fi

# Redis connection check
if [ -n "$REDIS_URL" ]; then
    REDIS_HOST=$(echo "$REDIS_URL" | sed -n 's/.*\/\/\([^:]*\).*/\1/p')
    REDIS_DB=$(echo "$REDIS_URL" | sed -n 's/.*\/\([0-9]*\)$/\1/p')
    log_success "Redis: $REDIS_HOST (db: ${REDIS_DB:-0})"
else
    log_warn "Redis: NOT CONFIGURED"
fi

# Centrifugo connection check
if [ -n "$CENTRIFUGO_URL" ] || [ -n "$NEXT_PUBLIC_CENTRIFUGO_URL" ]; then
    log_success "Centrifugo: ws.codeb.kr"
else
    log_warn "Centrifugo: NOT CONFIGURED"
fi

# NextAuth URL check
if [ -n "$NEXTAUTH_URL" ]; then
    log_success "NextAuth: $NEXTAUTH_URL"
else
    log_warn "NextAuth: NOT CONFIGURED (authentication may fail)"
fi

echo ""

# Run Prisma migrations if enabled
if [ "$RUN_MIGRATIONS" = "true" ] && [ -n "$DATABASE_URL" ]; then
    log_info "Running Prisma migrations..."
    npx prisma migrate deploy 2>/dev/null || {
        log_warn "migrate deploy failed, trying db push..."
        npx prisma db push --accept-data-loss 2>/dev/null || log_warn "Skipped or already up to date"
    }
    echo ""
fi

# Wait for database if configured
if [ "$WAIT_FOR_DB" = "true" ] && [ -n "$DATABASE_URL" ]; then
    DB_HOST=$(echo "$DATABASE_URL" | sed -n 's/.*@\([^:\/]*\).*/\1/p')
    DB_PORT=$(echo "$DATABASE_URL" | sed -n 's/.*:\([0-9]*\)\/.*/\1/p')
    DB_PORT=${DB_PORT:-5432}

    log_info "Waiting for database at $DB_HOST:$DB_PORT..."
    ATTEMPTS=0
    MAX_ATTEMPTS=30

    while [ $ATTEMPTS -lt $MAX_ATTEMPTS ]; do
        if nc -z "$DB_HOST" "$DB_PORT" 2>/dev/null; then
            log_success "Database is ready!"
            break
        fi
        ATTEMPTS=$((ATTEMPTS + 1))
        log_info "Attempt $ATTEMPTS/$MAX_ATTEMPTS, retrying in 2s..."
        sleep 2
    done

    if [ $ATTEMPTS -eq $MAX_ATTEMPTS ]; then
        log_error "Database connection timeout"
    fi
    echo ""
fi

log_info "Launching application..."
echo "========================================"
echo ""

# Execute the main command
exec "$@"
