# ==============================================================================
# worb CMS - Optimized Multi-stage Dockerfile
# Generated by CodeB CLI v4.2.0
# Date: 2026-01-07
# ==============================================================================
# Infrastructure:
#   - App Server: app.codeb.kr (158.247.203.55)
#   - Database: db.codeb.kr (PostgreSQL 5432)
#   - Redis: db.codeb.kr (Redis 6379)
#   - WebSocket: ws.codeb.kr (Centrifugo 8000)
# ==============================================================================
# Blue-Green Slot Deployment:
#   - Production Blue:  Port 4000 (worb-blue.service)
#   - Production Green: Port 4001 (worb-green.service)
#   - Staging Blue:     Port 4500 (worb-staging-blue.service)
#   - Staging Green:    Port 4501 (worb-staging-green.service)
# ==============================================================================
# v4.2.0 Changes:
#   - Added Sentry CLI for source maps upload
#   - Improved layer caching with .dockerignore
#   - Added multi-platform support (amd64/arm64)
# ==============================================================================

# ==============================================================================
# Stage 1: Dependencies
# ==============================================================================
FROM node:20-slim AS deps

# Build argument for GitHub Package Registry authentication
ARG NPM_TOKEN

# Install system dependencies for Prisma and native modules
RUN apt-get update && apt-get install -y --no-install-recommends \
    openssl \
    ca-certificates \
    python3 \
    make \
    g++ \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Configure npm for GitHub Package Registry
RUN echo "//npm.pkg.github.com/:_authToken=${NPM_TOKEN}" > .npmrc && \
    echo "@codeblabdev-max:registry=https://npm.pkg.github.com" >> .npmrc

# Copy Prisma schema first (needed for postinstall)
COPY prisma ./prisma

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies
# --legacy-peer-deps for React 19 compatibility
# --ignore-scripts to skip postinstall, run prisma generate manually
RUN npm ci --ignore-scripts --legacy-peer-deps && \
    npx prisma generate && \
    rm -f .npmrc

# ==============================================================================
# Stage 2: Builder
# ==============================================================================
FROM node:20-slim AS builder

# Build arguments for versioning
ARG BUILDTIME
ARG VERSION
ARG REVISION

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    openssl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy dependencies from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy source code
COPY . .

# Set build-time environment variables (placeholders - overridden at runtime)
ENV DATABASE_URL="postgresql://placeholder:placeholder@localhost:5432/placeholder?schema=public"
ENV NEXTAUTH_URL="http://localhost:3000"
ENV NEXTAUTH_SECRET="build-time-secret-placeholder-32chars"

# Regenerate Prisma Client for builder environment
RUN npx prisma generate

# Build Next.js (standalone mode)
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build:production

# ==============================================================================
# Stage 3: Production Runner
# ==============================================================================
FROM node:20-slim AS runner

# Build arguments for labels
ARG BUILDTIME
ARG VERSION
ARG REVISION

# Labels for image metadata
LABEL org.opencontainers.image.title="worb CMS"
LABEL org.opencontainers.image.description="worb CMS - Project Management System"
LABEL org.opencontainers.image.vendor="CodeB"
LABEL org.opencontainers.image.source="https://github.com/codeblabdev-max/workb"
LABEL org.opencontainers.image.version="${VERSION:-latest}"
LABEL org.opencontainers.image.revision="${REVISION:-unknown}"
LABEL org.opencontainers.image.created="${BUILDTIME:-unknown}"

WORKDIR /app

# Environment configuration
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Install runtime dependencies only
RUN apt-get update && apt-get install -y --no-install-recommends \
    openssl \
    ca-certificates \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Create non-root user for security
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy necessary files from builder
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder /app/node_modules/@prisma ./node_modules/@prisma

# Copy entrypoint script
COPY docker-entrypoint.sh /app/docker-entrypoint.sh

# Set permissions
RUN chmod +x /app/docker-entrypoint.sh && \
    chown -R nextjs:nodejs /app

# Switch to non-root user
USER nextjs

# Expose port (configurable via PORT env)
# Blue-Green slots use different ports
EXPOSE 3000 4000 4001 4500 4501

# Runtime configuration - PORT is set by Quadlet
ENV HOSTNAME="0.0.0.0"

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
    CMD curl -sf http://localhost:${PORT:-3000}/api/health || exit 1

# Entrypoint and command
ENTRYPOINT ["/app/docker-entrypoint.sh"]
CMD ["node", "server.js"]
