#!/bin/sh
set -e

# ==============================================================================
# worb CMS - Docker Entrypoint
# Generated by CodeB CLI v3.0.3
# ==============================================================================

echo "🚀 Starting worb CMS..."
echo "   Environment: ${NODE_ENV:-production}"
echo "   Port: ${PORT:-3000}"

# Load environment variables from .env file if it exists
if [ -f /app/.env ]; then
    echo "📄 Loading environment variables from /app/.env"
    export $(cat /app/.env | grep -v '^#' | xargs)
fi

# Debug: Print connection status (masked for security)
echo ""
echo "📊 Connection Status:"

if [ -n "$DATABASE_URL" ]; then
    echo "   ✅ DATABASE_URL is set (length: ${#DATABASE_URL})"
else
    echo "   ⚠️ WARNING: DATABASE_URL is not set!"
fi

if [ -n "$REDIS_URL" ]; then
    echo "   ✅ REDIS_URL is set (length: ${#REDIS_URL})"
else
    echo "   ⚠️ WARNING: REDIS_URL is not set!"
fi

if [ -n "$CENTRIFUGO_URL" ] || [ -n "$NEXT_PUBLIC_CENTRIFUGO_URL" ]; then
    echo "   ✅ Centrifugo URL is set"
else
    echo "   ⚠️ WARNING: Centrifugo URL is not set!"
fi

echo ""

# Run Prisma migrations if enabled
if [ -n "$DATABASE_URL" ] && [ "$RUN_MIGRATIONS" = "true" ]; then
    echo "🔄 Running Prisma migrations..."
    npx prisma db push --accept-data-loss || echo "⚠️ Migration failed or skipped"
fi

echo "✨ Starting application..."
echo ""

# Execute the main command
exec "$@"
