#!/bin/sh
set -e

# ==============================================================================
# worb CMS - Docker Entrypoint
# Generated by CodeB CLI v3.3.0
# Date: 2025-12-22
# ==============================================================================

echo "========================================"
echo " worb CMS Container Starting"
echo "========================================"
echo "Environment: ${NODE_ENV:-production}"
echo "Port: ${PORT:-3000}"
echo "Hostname: ${HOSTNAME:-0.0.0.0}"
echo ""

# Load environment variables from .env file if exists
if [ -f /app/.env ]; then
    echo "[ENV] Loading from /app/.env"
    set -a
    . /app/.env
    set +a
fi

# Connection status check
echo "[Status] Checking connections..."

if [ -n "$DATABASE_URL" ]; then
    DB_HOST=$(echo "$DATABASE_URL" | sed -n 's/.*@\([^:\/]*\).*/\1/p')
    echo "  - Database: $DB_HOST (configured)"
else
    echo "  - Database: NOT CONFIGURED"
fi

if [ -n "$REDIS_URL" ]; then
    REDIS_HOST=$(echo "$REDIS_URL" | sed -n 's/.*\/\/\([^:]*\).*/\1/p')
    echo "  - Redis: $REDIS_HOST (configured)"
else
    echo "  - Redis: NOT CONFIGURED"
fi

if [ -n "$CENTRIFUGO_URL" ] || [ -n "$NEXT_PUBLIC_CENTRIFUGO_URL" ]; then
    echo "  - Centrifugo: ws.codeb.kr (configured)"
else
    echo "  - Centrifugo: NOT CONFIGURED"
fi

echo ""

# Run Prisma migrations if enabled
if [ "$RUN_MIGRATIONS" = "true" ] && [ -n "$DATABASE_URL" ]; then
    echo "[Migration] Running Prisma migrations..."
    npx prisma migrate deploy 2>/dev/null || {
        echo "[Migration] migrate deploy failed, trying db push..."
        npx prisma db push --accept-data-loss 2>/dev/null || echo "[Migration] Skipped or already up to date"
    }
    echo ""
fi

echo "[Start] Launching application..."
echo "========================================"
echo ""

# Execute the main command
exec "$@"
