# ==============================================================================
# worb CMS - Optimized Multi-stage Dockerfile
# Generated by CodeB CLI v3.3.0
# Date: 2025-12-22
# ==============================================================================
# Infrastructure:
#   - App Server: app.codeb.kr (158.247.203.55)
#   - Database: db.codeb.kr (PostgreSQL 5432)
#   - Redis: db.codeb.kr (Redis 6379)
#   - WebSocket: ws.codeb.kr (Centrifugo 8000)
# ==============================================================================

# ==============================================================================
# Stage 1: Dependencies
# ==============================================================================
FROM node:20-slim AS deps

# Install system dependencies for Prisma
RUN apt-get update && apt-get install -y \
    openssl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy Prisma schema first (needed for postinstall)
COPY prisma ./prisma

# Copy package files
COPY package.json package-lock.json* ./

# Install dependencies (skip postinstall, run prisma generate manually)
RUN npm ci --ignore-scripts && \
    npx prisma generate

# ==============================================================================
# Stage 2: Builder
# ==============================================================================
FROM node:20-slim AS builder

# Build arguments for versioning
ARG BUILDTIME
ARG VERSION
ARG REVISION

# Install system dependencies
RUN apt-get update && apt-get install -y \
    openssl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy dependencies from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy source code
COPY . .

# Set build-time environment variables (placeholders - overridden at runtime)
ENV DATABASE_URL="postgresql://placeholder:placeholder@localhost:5432/placeholder?schema=public"
ENV NEXTAUTH_URL="http://localhost:3000"
ENV NEXTAUTH_SECRET="build-time-secret-placeholder-32chars"

# Generate Prisma Client
RUN npx prisma generate

# Build Next.js (standalone mode)
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build:production

# ==============================================================================
# Stage 3: Production Runner
# ==============================================================================
FROM node:20-slim AS runner

# Labels for image metadata
LABEL org.opencontainers.image.title="worb CMS"
LABEL org.opencontainers.image.description="worb CMS - Project Management System"
LABEL org.opencontainers.image.vendor="CodeB"
LABEL org.opencontainers.image.source="https://github.com/codeblabdev-max/workb"
LABEL org.opencontainers.image.version="${VERSION:-latest}"
LABEL org.opencontainers.image.revision="${REVISION:-unknown}"
LABEL org.opencontainers.image.created="${BUILDTIME:-unknown}"

WORKDIR /app

# Environment configuration
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Install runtime dependencies
RUN apt-get update && apt-get install -y \
    openssl \
    ca-certificates \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Create non-root user for security
RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 nextjs

# Copy necessary files from builder
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder /app/node_modules/@prisma ./node_modules/@prisma

# Copy entrypoint script
COPY docker-entrypoint.sh /app/docker-entrypoint.sh

# Set permissions
RUN chmod +x /app/docker-entrypoint.sh && \
    chown -R nextjs:nodejs /app

# Switch to non-root user
USER nextjs

# Expose port (configurable via PORT env)
EXPOSE 3000 4000 4500

# Runtime configuration - PORT is set by Quadlet, not hardcoded here
ENV HOSTNAME="0.0.0.0"

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=60s --retries=3 \
    CMD curl -sf http://localhost:${PORT}/api/health || exit 1

# Entrypoint and command
ENTRYPOINT ["/app/docker-entrypoint.sh"]
CMD ["node", "server.js"]
